### ISSUE TITLE
Add ability to specify route namespace

### ISSUE THREAD

**Issue by dominic-ks** [dominic-ks/bdvs-password-reset#4]
Originally request here:

- https://wordpress.org/support/topic/add-ability-to-specify-route-namespace/

Add new filters to allow developers to customise the name space for the API calls. The filter will need to be added to 3 files and could be added directly inline in the register_rest_route parameter.

- /inc/api/api.route.reset-password.php
- /inc/api/api.route.set-password.php
- /inc/api/api.route.validate-code.php

The filter name should follow the general naming convention that's been used for the other hooks in this plugin.

**Comment by wpamitkumar** [comment]
Hi @dominic-ks, Please review the PR. [#5 ]

**Comment by dominic-ks** [comment]
All done, thanks very much.
